### ISSUE TITLE
Ubicación de aventuras

### ISSUE THREAD

**Issue by Federico-G** [COBIT-19/zork#2]
Las aventuras deberían estar bien ubicadas. Ahora solo tienen una que es la de pruebas creo, pero de todas maneras no debería estar en la raíz del proyecto

https://github.com/COBIT-19/zork/blob/master/escenario1.json

**Comment by juanpablodelgreco** [comment]
Arreglado

**Comment by juanpablodelgreco** [comment]
[https://github.com/COBIT-19/zork/commit/ea3f75ee883dd04597c41b5064352a1a4d0dec59](url)

**Comment by juanpablodelgreco** [comment]
https://github.com/COBIT-19/zork/commit/ea3f75ee883dd04597c41b5064352a1a4d0dec59
