### ISSUE TITLE
Uso de constantes

### ISSUE THREAD

**Issue by Federico-G** [COBIT-19/zork#4]
En la clase Noun, los atributos géneros y números deberían ser ENUM
En Java se prefieren los enum por encima de las constantes. Nos brindan más flexibilidad.

https://github.com/COBIT-19/zork/blob/32a6f4eb2d686435012459f29575e885fb7e586f/src/entities/Noun.java#L3

**Comment by juanpablodelgreco** [comment]
Arreglado

**Comment by juanpablodelgreco** [comment]
https://github.com/COBIT-19/zork/commit/6592226139eefc20c80188a39ad9feb7f9b6801b
