### ISSUE TITLE
Objetos concretos antes que Strings

### ISSUE THREAD

**Issue by Federico-G** [COBIT-19/zork#5]
Voy a tomar el siguiente código como ejemplo, pero va para varios casos donde ocurre lo mismo

https://github.com/COBIT-19/zork/blob/32a6f4eb2d686435012459f29575e885fb7e586f/src/entities/Player.java#L87

Muchos de estos métodos son realizados después de procesar de alguna manera el texto. Por lo tanto, en teoría, deberían tener (en caso correcto) el objeto concreto del que se trata, y no un string.

En el ejemplo de más arriba, el item ya deberían saber cual es, así que se podría directamente mandar el objeto

**Comment by juanpablodelgreco** [comment]
https://github.com/COBIT-19/zork/commit/85638c835b302df99a6a4b77b64cdbbf8cbc0365

**Comment by Federico-G** [comment]
:+1:
